import { Request, Response } from 'express';
import { prisma } from '../config/database';
import { AppError } from '../utils/app-error';
import { requireCookbookRole } from '../services/access.service';
async function requireRecipeEdit(id:string,userId:string){const r=await prisma.recipe.findUnique({where:{id}});if(!r)throw new AppError(404,'La recette est introuvable.');if(r.authorId!==userId){if(!r.cookbookId)throw new AppError(403,"Vous ne pouvez pas modifier cette recette.");await requireCookbookRole(r.cookbookId,userId,'EDITOR');}return r;}
export async function listRecipes(req:Request,res:Response){const {search,cookbookId,tag,favorite}=req.query as Record<string,string>;const items=await prisma.recipe.findMany({where:{AND:[cookbookId?{cookbookId}: {},tag?{tags:{has:tag}}:{},search?{OR:[{title:{contains:search,mode:'insensitive'}},{description:{contains:search,mode:'insensitive'}},{tags:{has:search}}]}:{},favorite==='true'?{favorites:{some:{userId:req.user!.id}}}:{}, {OR:[{authorId:req.user!.id},{cookbook:{OR:[{ownerId:req.user!.id},{members:{some:{userId:req.user!.id}}}]}}]}]},include:{favorites:{where:{userId:req.user!.id}},_count:{select:{comments:true}}},orderBy:{updatedAt:'desc'}});res.json({success:true,data:items.map(r=>({...r,isFavorite:r.favorites.length>0,favorites:undefined}))});}
export async function getRecipe(req:Request,res:Response){const item=await prisma.recipe.findUnique({where:{id:req.params.id},include:{author:{select:{id:true,displayName:true}},comments:{include:{author:{select:{id:true,displayName:true}}},orderBy:{createdAt:'desc'}},favorites:{where:{userId:req.user!.id}}}});if(!item)throw new AppError(404,'La recette est introuvable.');if(item.authorId!==req.user!.id&&item.cookbookId)await requireCookbookRole(item.cookbookId,req.user!.id,'READER');else if(item.authorId!==req.user!.id)throw new AppError(403,"Vous n'avez pas accès à cette recette.");res.json({success:true,data:{...item,isFavorite:item.favorites.length>0,favorites:undefined}});}
export async function createRecipe(req:Request,res:Response){if(req.body.cookbookId)await requireCookbookRole(req.body.cookbookId,req.user!.id,'EDITOR');const item=await prisma.recipe.create({data:{...req.body,authorId:req.user!.id}});res.status(201).json({success:true,data:item});}
export async function updateRecipe(req:Request,res:Response){await requireRecipeEdit(req.params.id!,req.user!.id);const item=await prisma.recipe.update({where:{id:req.params.id},data:req.body});res.json({success:true,data:item});}
export async function deleteRecipe(req:Request,res:Response){await requireRecipeEdit(req.params.id!,req.user!.id);await prisma.recipe.delete({where:{id:req.params.id}});res.status(204).send();}
export async function toggleFavorite(req:Request,res:Response){const where={userId_recipeId:{userId:req.user!.id,recipeId:req.params.id!}};const existing=await prisma.favorite.findUnique({where});if(existing){await prisma.favorite.delete({where});res.json({success:true,data:{isFavorite:false}});}else{await prisma.favorite.create({data:{userId:req.user!.id,recipeId:req.params.id!}});res.status(201).json({success:true,data:{isFavorite:true}});}}
export async function addComment(req:Request,res:Response){const recipe=await prisma.recipe.findUnique({where:{id:req.params.id}});if(!recipe)throw new AppError(404,'La recette est introuvable.');if(recipe.cookbookId)await requireCookbookRole(recipe.cookbookId,req.user!.id,'COMMENTER');else if(recipe.authorId!==req.user!.id)throw new AppError(403,"Vous ne pouvez pas commenter cette recette.");const c=await prisma.comment.create({data:{content:req.body.content,recipeId:recipe.id,authorId:req.user!.id},include:{author:{select:{id:true,displayName:true}}}});res.status(201).json({success:true,data:c});}
