import { Router } from 'express';
import { register, login } from '../controllers/auth.controller';
import { getProfile, updateProfile } from '../controllers/user.controller';
import * as cookbook from '../controllers/cookbook.controller';
import * as recipe from '../controllers/recipe.controller';
import * as meal from '../controllers/meal-plan.controller';
import * as data from '../controllers/data.controller';
import { authenticate } from '../middlewares/auth.middleware';
import { validate } from '../middlewares/validate.middleware';
import { asyncHandler } from '../utils/async-handler';
import { registerSchema,loginSchema,profileSchema,cookbookSchema,cookbookUpdateSchema,memberSchema,recipeSchema,recipeUpdateSchema,idSchema,commentSchema,mealPlanSchema } from '../validators/schemas';
const r=Router();
r.get('/health',(_q,s)=>s.json({success:true,data:{status:'ok'}}));
r.post('/auth/register',validate(registerSchema),asyncHandler(register)); r.post('/auth/login',validate(loginSchema),asyncHandler(login));
r.use(authenticate);
r.get('/users/me',asyncHandler(getProfile)); r.patch('/users/me',validate(profileSchema),asyncHandler(updateProfile));
r.get('/cookbooks',asyncHandler(cookbook.listCookbooks)); r.post('/cookbooks',validate(cookbookSchema),asyncHandler(cookbook.createCookbook)); r.get('/cookbooks/:id',validate(idSchema),asyncHandler(cookbook.getCookbook)); r.patch('/cookbooks/:id',validate(cookbookUpdateSchema),asyncHandler(cookbook.updateCookbook)); r.delete('/cookbooks/:id',validate(idSchema),asyncHandler(cookbook.deleteCookbook)); r.post('/cookbooks/:id/members',validate(memberSchema),asyncHandler(cookbook.addMember));
r.get('/recipes',asyncHandler(recipe.listRecipes)); r.post('/recipes',validate(recipeSchema),asyncHandler(recipe.createRecipe)); r.get('/recipes/:id',validate(idSchema),asyncHandler(recipe.getRecipe)); r.patch('/recipes/:id',validate(recipeUpdateSchema),asyncHandler(recipe.updateRecipe)); r.delete('/recipes/:id',validate(idSchema),asyncHandler(recipe.deleteRecipe)); r.post('/recipes/:id/favorite',validate(idSchema),asyncHandler(recipe.toggleFavorite)); r.post('/recipes/:id/comments',validate(commentSchema),asyncHandler(recipe.addComment));
r.get('/meal-plans',asyncHandler(meal.listMealPlans)); r.post('/meal-plans',validate(mealPlanSchema),asyncHandler(meal.createMealPlan)); r.delete('/meal-plans/:id',validate(idSchema),asyncHandler(meal.deleteMealPlan));
r.get('/data/export',asyncHandler(data.exportData)); r.post('/data/import',asyncHandler(data.importData));
export default r;
